routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'QuoteController@index');
Route::resource('/quote', 'QuoteController');

app/Quote.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Quote extends Model
{
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/QuoteController.php
<?php

namespace App\Http\Controllers;

use App\Quote;
use Illuminate\Http\Request;

class QuoteController extends Controller
{
    public function __construct() {
        $this->middleware('auth')->except('index');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $quotes = Quote::all();
        return view('quote.index')->with('quotes', $quotes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('quote.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'quote' => 'required|max:255',
            'author' => 'required',
            'color' => 'in:green,orange,pink|required',
        ]);

        $quote = new Quote();
        $quote->quote = $request->quote;
        $quote->author = $request->author;
        $quote->color = $request->color;
        $quote->save();

        return redirect()->action('QuoteController@index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\quote  $quote
     * @return \Illuminate\Http\Response
     */
    public function show(quote $quote)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\quote  $quote
     * @return \Illuminate\Http\Response
     */
    public function edit(quote $quote)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\quote  $quote
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, quote $quote)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\quote  $quote
     * @return \Illuminate\Http\Response
     */
    public function destroy(quote $quote)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <!-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> -->
    <link href="{{ asset('css/materialize.min.css') }}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


</head>
<body>

    <!-- Account dropdown -->
    <ul id="account_dropdown" class="dropdown-content">
        <li><a href="#!">My quotes</a></li>
        <li class="divider"></li>
        <li>
            <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                Logout
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>

    <!-- Account dropdown for mobile nav - cannot use one dropdown source in Materialize -->
    <ul id="account_dropdown_mobile" class="dropdown-content">
        <li><a href="#!">My quotes</a></li>
        <li class="divider"></li>
        <li>
            <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                Logout
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </li>
    </ul>

    <nav style="margin-bottom: 50px;">
        <div class="nav-wrapper blue">
            <a href="{{ route('quote.index') }}" class="brand-logo center">QuoteApp</a>
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="{{ route('quote.index') }}">Home</a></li>
                @guest
                    <li><a href="{{ route('login') }}">Login</a></li>
                    <li><a href="{{ route('register') }}">Register</a></li>
                @else
                    <li><a href="{{ route('quote.create') }}">Add quote</a></li>
                    <!-- Dropdown Trigger -->
                    <li><a class="dropdown-button" href="#" data-activates="account_dropdown">{{ Auth::user()->name }}<i class="material-icons right">arrow_drop_down</i></a></li>
                @endguest
            </ul>
            <ul class="side-nav white" id="mobile-demo">
                <li><a href="{{ route('quote.index') }}" class="blue-text"><i class="material-icons blue-text">home</i>Home</a></li>
                @auth
                    <li><a href="{{ route('quote.create') }}" class="blue-text"><i class="material-icons blue-text">add_circle</i> Add quote</a></li>
                    <li><a class="dropdown-button" href="#" data-activates="account_dropdown_mobile"> <span class="blue-text">{{ Auth::user()->name }}</span><i class="material-icons right blue-text">arrow_drop_down</i></a></li>
                @else
                    <li><a href="{{ route('login') }}" class="blue-text"><i class="material-icons blue-text">account_box</i>Login</a></li>
                    <li><a href="{{ route('register') }}" class="blue-text"><i class="material-icons blue-text">supervisor_account</i>Register</a></li>
                @endauth
            </ul>
        </div>
    </nav>

    <div class="container">
        @yield('content')
    </div>



    <!-- Scripts -->
    <script src="{{ asset('js/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ asset('js/materialize.min.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/quote/create.blade.php
@extends('layouts/app')

@section('content')

    <div class="row">

        <form class="col s8 offset-s2" action="{{ route('quote.store') }}" method="POST">

            @if ($errors->any())
                <ul class="collection red-text">
                    @foreach ($errors->all() as $error)
                        <li class="collection-item"><i class="small material-icons red-text">error_outline</i> {{ $error }}</li>
                    @endforeach
                </ul>
            @endif

            <div class="row">
                <div class="input-field col s12">
                    <textarea id="quote_content" name="quote" type="text" class="materialize-textarea validate" required></textarea>
                    <label for="quote_content" data-error="This field is required!" data-success="">Quote</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <input id="quote_author" name="author" type="text" class="validate" required>
                    <label for="quote_author" data-error="This field is required!" data-success="">Author</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <select name="color">
                        <option value="" disabled selected>Select Your color</option>
                        <option value="green">Green</option>
                        <option value="orange">Orange</option>
                        <option value="pink">Pink</option>
                    </select>
                    <label>Select Your color</label>
                </div>
            </div>


            <div class="row">
                <button class="waves-effect waves-light btn blue darken-2" role="button" type="submit">Create</button>
            </div>
            {{ csrf_field() }}

        </form>

    </div>

@endsection

resources/views/quote/index.blade.php
@extends('layouts/app')

@section('content')




    <div class="row">
        @foreach ($quotes as $quote)

            <div class="col s12 l6">
                <div class="card {{ $quote->color }} lighten-2">
                    <div class="card-content white-text">
                        <p>{{ $quote->quote }}</p>
                        <p class="right-align">~ <i>{{ $quote->author }}</i></p>
                    </div>
                </div>
            </div>
        @endforeach

    </div>

@endsection